# Generated by Django 4.2.7 on 2023-11-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("acc_no", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("father_name", models.CharField(max_length=25)),
                ("mother_name", models.CharField(max_length=25)),
                ("dob", models.DateField()),
                ("balance", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("date", models.DateField()),
                ("amount", models.IntegerField()),
                ("transaction_id", models.CharField(max_length=30)),
                (
                    "acc_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mybankSQL.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_name", models.CharField(max_length=25)),
                ("sender_name", models.CharField(max_length=25)),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
                ("transaction_id", models.CharField(max_length=30)),
                (
                    "acc_no_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to="mybankSQL.account",
                    ),
                ),
                (
                    "acc_no_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to="mybankSQL.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=30)),
                (
                    "acc_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mybankSQL.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("date", models.DateField()),
                ("amount", models.IntegerField()),
                ("transaction_id", models.CharField(max_length=30)),
                (
                    "acc_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mybankSQL.account",
                    ),
                ),
            ],
        ),
    ]
