# Generated by Django 4.2.7 on 2023-11-24 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("acc_no", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
                ("father_name", models.CharField(blank=True, max_length=25, null=True)),
                ("mother_name", models.CharField(blank=True, max_length=25, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("balance", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccountID",
            fields=[
                (
                    "acc_no",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acc_no_reciever", models.IntegerField(blank=True, null=True)),
                (
                    "reciever_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("acc_no_sender", models.IntegerField(blank=True, null=True)),
                ("sender_name", models.CharField(blank=True, max_length=20, null=True)),
                ("Balance", models.IntegerField(blank=True, null=True)),
                ("Date", models.DateField(blank=True, null=True)),
                ("TID", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "transaction_category",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionID",
            fields=[
                (
                    "transaction_id",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("amount", models.IntegerField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "acc_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mybankSQL.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("sender_name", models.CharField(blank=True, max_length=25, null=True)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "acc_no_receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to="mybankSQL.account",
                    ),
                ),
                (
                    "acc_no_sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to="mybankSQL.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("amount", models.IntegerField(blank=True, default="0", null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "acc_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mybankSQL.account",
                    ),
                ),
            ],
        ),
    ]
