# Generated by Django 4.2.7 on 2023-11-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mybankSQL", "0002_alter_deposit_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
