# Generated by Django 4.2.7 on 2023-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mybankSQL", "0003_alter_deposit_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountID",
            fields=[
                (
                    "acc_no",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionID",
            fields=[
                (
                    "transaction_id",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ID",
        ),
    ]
