# Generated by Django 4.2.7 on 2023-11-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mybankSQL", "0004_accountid_transactionid_delete_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acc_no_reciever", models.IntegerField()),
                ("reciever_name", models.CharField(max_length=20)),
                ("acc_no_sender", models.IntegerField()),
                ("sender_name", models.CharField(max_length=20)),
                ("Balance", models.IntegerField()),
                ("Date", models.DateField()),
                ("TID", models.CharField(max_length=30)),
                ("transaction_category", models.CharField(max_length=20)),
            ],
        ),
    ]
