# Generated by Django 4.2.7 on 2023-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mybankSQL", "0005_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demo",
            name="acc_no_reciever",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="demo",
            name="acc_no_sender",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="demo",
            name="reciever_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="demo",
            name="sender_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
