# Generated by Django 4.2.7 on 2023-11-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mybankSQL", "0007_remove_account_dob_remove_demo_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="account",
            name="father_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="mother_name",
        ),
        migrations.RemoveField(
            model_name="demo",
            name="Balance",
        ),
        migrations.RemoveField(
            model_name="demo",
            name="TID",
        ),
        migrations.RemoveField(
            model_name="demo",
            name="acc_no_sender",
        ),
        migrations.RemoveField(
            model_name="demo",
            name="sender_name",
        ),
        migrations.RemoveField(
            model_name="demo",
            name="transaction_category",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="acc_no_sender",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="receiver_name",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="sender_name",
        ),
        migrations.RemoveField(
            model_name="withdrawal",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="withdrawal",
            name="transaction_id",
        ),
    ]
