# Generated by Django 4.2.7 on 2023-11-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "mybankSQL",
            "0008_remove_account_balance_remove_account_father_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="balance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="father_name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="mother_name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="Balance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="Date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="TID",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="acc_no_sender",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="sender_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="transaction_category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="transfer",
            name="acc_no_sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="mybankSQL.account",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transfer",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transfer",
            name="receiver_name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="transfer",
            name="sender_name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="acc_no_receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="mybankSQL.account",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
